/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Novu } from "@fern-api/novu";

export interface MessagesControllerGetMessagesRequest {
    /**
     * The channel for the messages you wish to list
     */
    channel?: Novu.ChannelPreferenceType;
    /**
     * The subscriberId for the subscriber you like to list messages for
     */
    subscriberId?: string;
    /**
     * The number of messages to fetch, defaults to 10
     */
    limit?: number;
    /**
     * The page to fetch, defaults to 0
     */
    page?: number;
}
