/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * It is used to display the Avatar of the provided actor's subscriber id or actor object.
 *     If a new actor object is provided, we will create a new subscriber in our system
 *
 */
export type TriggerEventToAllRequestDtoActor = unknown;
