/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Novu } from "@fern-api/novu";

export interface TriggerEventToAllRequestDto {
    /** The trigger identifier associated for the template you wish to send. This identifier can be found on the template page. */
    name: string;
    /**
     * The payload object is used to pass additional custom information that could be used to render the template, or perform routing rules based on it.
     *       This data will also be available when fetching the notifications feed from the API to display certain parts of the UI.
     */
    payload: Record<string, unknown>;
    /** This could be used to override provider specific configurations */
    overrides?: Record<string, unknown>;
    /** A unique identifier for this transaction, we will generated a UUID if not provided. */
    transactionId?: string;
    actor?: Novu.TriggerEventToAllRequestDtoActor | undefined;
}
