/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const CreateIntegrationRequestDto: core.serialization.ObjectSchema<
    serializers.CreateIntegrationRequestDto.Raw,
    Novu.CreateIntegrationRequestDto
> = core.serialization.object({
    providerId: core.serialization.string(),
    channel: core.serialization.lazy(async () => (await import("../../..")).ChannelPreferenceType),
    credentials: core.serialization.lazyObject(async () => (await import("../../..")).CredentialsDto),
    active: core.serialization.boolean(),
    check: core.serialization.boolean(),
});

export declare namespace CreateIntegrationRequestDto {
    interface Raw {
        providerId: string;
        channel: serializers.ChannelPreferenceType.Raw;
        credentials: serializers.CredentialsDto.Raw;
        active: boolean;
        check: boolean;
    }
}
