/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const CreateEnvironmentRequestDtoChannel: core.serialization.Schema<
    serializers.CreateEnvironmentRequestDtoChannel.Raw,
    Novu.CreateEnvironmentRequestDtoChannel
> = core.serialization.enum_(["in_app", "email", "sms", "chat", "push"]);

export declare namespace CreateEnvironmentRequestDtoChannel {
    type Raw = "in_app" | "email" | "sms" | "chat" | "push";
}
