/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const UpdateIntegrationRequestDto: core.serialization.ObjectSchema<
    serializers.UpdateIntegrationRequestDto.Raw,
    Novu.UpdateIntegrationRequestDto
> = core.serialization.object({
    active: core.serialization.boolean(),
    credentials: core.serialization.lazyObject(async () => (await import("../../..")).CredentialsDto),
    check: core.serialization.boolean(),
});

export declare namespace UpdateIntegrationRequestDto {
    interface Raw {
        active: boolean;
        credentials: serializers.CredentialsDto.Raw;
        check: boolean;
    }
}
