/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Subscriber credentials for channel
 */
export type ChannelSettingsProviderId = "slack" | "discord" | "msteams" | "fcm" | "apns" | "expo";

export const ChannelSettingsProviderId = {
    Slack: "slack",
    Discord: "discord",
    Msteams: "msteams",
    Fcm: "fcm",
    Apns: "apns",
    Expo: "expo",
} as const;
