/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Novu } from "@fern-api/novu";

export interface ChannelPreference {
    type: Novu.ChannelPreferenceType;
    /** If channel is enabled or not */
    enabled: boolean;
}
