/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ChannelCredentials {
    /** Webhook url used by chat app integrations. The webhook should be obtained from the chat app provider. */
    webhookUrl: string;
    /** Contains an array of the subscriber device tokens for a given provider. Used on Push integrations */
    deviceTokens?: string[];
}
