/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type EmailBlockStylesTextAlign = "left" | "right" | "center";

export const EmailBlockStylesTextAlign = {
    Left: "left",
    Right: "right",
    Center: "center",
} as const;
