/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type EmailBlockType = "text" | "button";

export const EmailBlockType = {
    Text: "text",
    Button: "button",
} as const;
