/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Novu } from "@fern-api/novu";

export interface EmailBlock {
    type: Novu.EmailBlockType;
    content: string;
    url?: string;
    styles?: Novu.EmailBlockStyles;
}
