/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Novu } from "@fern-api/novu";

export interface MarkMessageAsRequestDto {
    messageId?: Novu.MarkMessageAsRequestDtoMessageId;
    mark: Novu.MarkMessageFields;
}
