/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type MessageActionResultType = "primary" | "secondary" | "clicked";

export const MessageActionResultType = {
    Primary: "primary",
    Secondary: "secondary",
    Clicked: "clicked",
} as const;
