/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Novu } from "@fern-api/novu";

export interface MessageCta {
    type: Novu.MessageCtaType;
    data: Novu.MessageCtaData;
    action?: Novu.MessageAction;
}
