/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type MessageActionType = "pending" | "done";

export const MessageActionType = {
    Pending: "pending",
    Done: "done",
} as const;
