/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type MessageResponseDtoStatus = "sent" | "error" | "warning";

export const MessageResponseDtoStatus = {
    Sent: "sent",
    Error: "error",
    Warning: "warning",
} as const;
