/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Novu } from "@fern-api/novu";

export interface Preference {
    /** Sets if the notification template is fully enabled for all channels or not for the subscriber. */
    enabled: boolean;
    channels: Novu.PreferenceChannels;
}
