/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Novu } from "@fern-api/novu";

export interface SubscribersResponseDto {
    /** The current page of the paginated response */
    page: number;
    /** Total count of subscribers matching the query */
    totalCount: number;
    /** Number of subscribers on each page */
    pageSize: number;
    /** The list of subscribers matching the query */
    data: Novu.SubscriberResponseDto[];
}
