/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TemplateResponse {
    /** Unique identifier of the notification template */
    id: string;
    /** Name of the notification template */
    name: string;
    /** Critical templates will always be delivered to the end user and should be hidden from the subscriber preferences screen */
    critical: boolean;
}
