/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UpdateSubscriberRequestDto {
    email?: string;
    firstName?: string;
    lastName?: string;
    phone?: string;
    avatar?: string;
    locale?: string;
    data?: Record<string, unknown>;
}
