/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The provider identifier for the credentials
 */
export type UpdateSubscriberChannelRequestDtoProviderId = "slack" | "discord" | "msteams" | "fcm" | "apns" | "expo";

export const UpdateSubscriberChannelRequestDtoProviderId = {
    Slack: "slack",
    Discord: "discord",
    Msteams: "msteams",
    Fcm: "fcm",
    Apns: "apns",
    Expo: "expo",
} as const;
