/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const BulkTriggerEventDto: core.serialization.ObjectSchema<
    serializers.BulkTriggerEventDto.Raw,
    Novu.BulkTriggerEventDto
> = core.serialization.object({
    events: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("../../..")).TriggerEventRequestDto)
    ),
});

export declare namespace BulkTriggerEventDto {
    interface Raw {
        events: serializers.TriggerEventRequestDto.Raw[];
    }
}
