/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const TopicPayloadDtoType: core.serialization.Schema<
    serializers.TopicPayloadDtoType.Raw,
    Novu.TopicPayloadDtoType
> = core.serialization.string();

export declare namespace TopicPayloadDtoType {
    type Raw = string;
}
