/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const TriggerEventRequestDtoActor: core.serialization.Schema<
    serializers.TriggerEventRequestDtoActor.Raw,
    Novu.TriggerEventRequestDtoActor
> = core.serialization.unknown();

export declare namespace TriggerEventRequestDtoActor {
    type Raw = unknown;
}
