/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const TriggerEventResponseDtoStatus: core.serialization.Schema<
    serializers.TriggerEventResponseDtoStatus.Raw,
    Novu.TriggerEventResponseDtoStatus
> = core.serialization.enum_(["processed", "trigger_not_active", "subscriber_id_missing", "error"]);

export declare namespace TriggerEventResponseDtoStatus {
    type Raw = "processed" | "trigger_not_active" | "subscriber_id_missing" | "error";
}
