/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface FilterLayoutsResponseDto {
    data: string[];
    page: number;
    pageSize: number;
    totalCount: number;
}
