/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class NovuTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, NovuTimeoutError.prototype);
    }
}
