/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const FilterLayoutsResponseDto: core.serialization.ObjectSchema<
    serializers.FilterLayoutsResponseDto.Raw,
    Novu.FilterLayoutsResponseDto
> = core.serialization.object({
    data: core.serialization.list(core.serialization.string()),
    page: core.serialization.number(),
    pageSize: core.serialization.number(),
    totalCount: core.serialization.number(),
});

export declare namespace FilterLayoutsResponseDto {
    interface Raw {
        data: string[];
        page: number;
        pageSize: number;
        totalCount: number;
    }
}
