/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The status enum for the performed action
 */
export type DeleteMessageResponseDtoStatus = "deleted";

export const DeleteMessageResponseDtoStatus = {
    Deleted: "deleted",
} as const;
