/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetMessagesParametersSchema = "in_app" | "email" | "sms" | "chat" | "push";

export const GetMessagesParametersSchema = {
    InApp: "in_app",
    Email: "email",
    Sms: "sms",
    Chat: "chat",
    Push: "push",
} as const;
