/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ChangeResponseDtoProperties =
    | "Feed"
    | "MessageTemplate"
    | "Layout"
    | "DefaultLayout"
    | "NotificationTemplate"
    | "NotificationGroup";

export const ChangeResponseDtoProperties = {
    Feed: "Feed",
    MessageTemplate: "MessageTemplate",
    Layout: "Layout",
    DefaultLayout: "DefaultLayout",
    NotificationTemplate: "NotificationTemplate",
    NotificationGroup: "NotificationGroup",
} as const;
