/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const ChangeResponseDtoProperties: core.serialization.Schema<
    serializers.ChangeResponseDtoProperties.Raw,
    Novu.ChangeResponseDtoProperties
> = core.serialization.enum_([
    "Feed",
    "MessageTemplate",
    "Layout",
    "DefaultLayout",
    "NotificationTemplate",
    "NotificationGroup",
]);

export declare namespace ChangeResponseDtoProperties {
    type Raw = "Feed" | "MessageTemplate" | "Layout" | "DefaultLayout" | "NotificationTemplate" | "NotificationGroup";
}
