/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const ChangesResponseDto: core.serialization.ObjectSchema<
    serializers.ChangesResponseDto.Raw,
    Novu.ChangesResponseDto
> = core.serialization.object({
    totalCount: core.serialization.number(),
    data: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("../../..")).ChangeResponseDto)
    ),
    pageSize: core.serialization.number(),
    page: core.serialization.number(),
});

export declare namespace ChangesResponseDto {
    interface Raw {
        totalCount: number;
        data: serializers.ChangeResponseDto.Raw[];
        pageSize: number;
        page: number;
    }
}
