/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const DeleteMessageResponseDto: core.serialization.ObjectSchema<
    serializers.DeleteMessageResponseDto.Raw,
    Novu.DeleteMessageResponseDto
> = core.serialization.object({
    acknowledged: core.serialization.boolean(),
    status: core.serialization.lazy(async () => (await import("../../..")).DeleteMessageResponseDtoStatus),
});

export declare namespace DeleteMessageResponseDto {
    interface Raw {
        acknowledged: boolean;
        status: serializers.DeleteMessageResponseDtoStatus.Raw;
    }
}
