/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const DeleteMessageResponseDtoStatus: core.serialization.Schema<
    serializers.DeleteMessageResponseDtoStatus.Raw,
    Novu.DeleteMessageResponseDtoStatus
> = core.serialization.enum_(["deleted"]);

export declare namespace DeleteMessageResponseDtoStatus {
    type Raw = "deleted";
}
