/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const CreateTopicResponseDto: core.serialization.ObjectSchema<
    serializers.CreateTopicResponseDto.Raw,
    Novu.CreateTopicResponseDto
> = core.serialization.object({});

export declare namespace CreateTopicResponseDto {
    interface Raw {}
}
