/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const CreateTopicRequestDto: core.serialization.ObjectSchema<
    serializers.CreateTopicRequestDto.Raw,
    Novu.CreateTopicRequestDto
> = core.serialization.object({
    key: core.serialization.string(),
    name: core.serialization.string(),
});

export declare namespace CreateTopicRequestDto {
    interface Raw {
        key: string;
        name: string;
    }
}
