/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const GetTopicResponseDto: core.serialization.ObjectSchema<
    serializers.GetTopicResponseDto.Raw,
    Novu.GetTopicResponseDto
> = core.serialization.object({
    id: core.serialization.property("_id", core.serialization.string().optional()),
    organizationId: core.serialization.property("_organizationId", core.serialization.string()),
    environmentId: core.serialization.property("_environmentId", core.serialization.string()),
    key: core.serialization.string(),
    name: core.serialization.string(),
    subscribers: core.serialization.list(core.serialization.string()),
});

export declare namespace GetTopicResponseDto {
    interface Raw {
        _id?: string | null;
        _organizationId: string;
        _environmentId: string;
        key: string;
        name: string;
        subscribers: string[];
    }
}
