/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const RemoveSubscribersRequestDto: core.serialization.ObjectSchema<
    serializers.RemoveSubscribersRequestDto.Raw,
    Novu.RemoveSubscribersRequestDto
> = core.serialization.object({
    subscribers: core.serialization.list(core.serialization.string()),
});

export declare namespace RemoveSubscribersRequestDto {
    interface Raw {
        subscribers: string[];
    }
}
