/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const RenameTopicRequestDto: core.serialization.ObjectSchema<
    serializers.RenameTopicRequestDto.Raw,
    Novu.RenameTopicRequestDto
> = core.serialization.object({
    name: core.serialization.string(),
});

export declare namespace RenameTopicRequestDto {
    interface Raw {
        name: string;
    }
}
