/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const ExecutionDetailsResponseDto: core.serialization.ObjectSchema<
    serializers.ExecutionDetailsResponseDto.Raw,
    Novu.ExecutionDetailsResponseDto
> = core.serialization.object({
    id: core.serialization.property("_id", core.serialization.string().optional()),
    organizationId: core.serialization.property("_organizationId", core.serialization.string()),
    jobId: core.serialization.property("_jobId", core.serialization.string()),
    environmentId: core.serialization.property("_environmentId", core.serialization.string()),
    notificationId: core.serialization.property("_notificationId", core.serialization.string()),
    notificationTemplateId: core.serialization.property("_notificationTemplateId", core.serialization.string()),
    subscriberId: core.serialization.property("_subscriberId", core.serialization.string()),
    messageId: core.serialization.property("_messageId", core.serialization.string().optional()),
    providerId: core.serialization.string().optional(),
    transactionId: core.serialization.string(),
    channel: core.serialization
        .lazy(async () => (await import("../../..")).ExecutionDetailsResponseDtoChannel)
        .optional(),
    detail: core.serialization.string(),
    source: core.serialization.lazy(async () => (await import("../../..")).ExecutionDetailsResponseDtoSource),
    status: core.serialization.lazy(async () => (await import("../../..")).ExecutionDetailsResponseDtoStatus),
    isTest: core.serialization.boolean(),
    isRetry: core.serialization.boolean(),
    createdAt: core.serialization.string().optional(),
});

export declare namespace ExecutionDetailsResponseDto {
    interface Raw {
        _id?: string | null;
        _organizationId: string;
        _jobId: string;
        _environmentId: string;
        _notificationId: string;
        _notificationTemplateId: string;
        _subscriberId: string;
        _messageId?: string | null;
        providerId?: string | null;
        transactionId: string;
        channel?: serializers.ExecutionDetailsResponseDtoChannel.Raw | null;
        detail: string;
        source: serializers.ExecutionDetailsResponseDtoSource.Raw;
        status: serializers.ExecutionDetailsResponseDtoStatus.Raw;
        isTest: boolean;
        isRetry: boolean;
        createdAt?: string | null;
    }
}
