/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ISubscribersDefine {
    firstName?: string;
    lastName?: string;
    email?: string;
    phone?: string;
    avatar?: string;
    locale?: string;
    subscriberId?: string;
}
