/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Status for trigger
 */
export type TriggerEventResponseDtoStatus = "processed" | "trigger_not_active" | "subscriber_id_missing" | "error";

export const TriggerEventResponseDtoStatus = {
    Processed: "processed",
    TriggerNotActive: "trigger_not_active",
    SubscriberIdMissing: "subscriber_id_missing",
    Error: "error",
} as const;
