/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { ISubscribersDefine } from "./ISubscribersDefine";
import { TopicPayloadDto } from "./TopicPayloadDto";

export type TriggerEventRequestDtoTo =
    | string
    | ISubscribersDefine
    | (string | ISubscribersDefine | TopicPayloadDto)[]
    | undefined;
