/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SubscriberPayloadDto } from "./SubscriberPayloadDto";
import { TopicPayloadDto } from "./TopicPayloadDto";

export type TriggerEventRequestDtoTo =
    | string
    | SubscriberPayloadDto
    | (string | SubscriberPayloadDto | TopicPayloadDto)[];
