/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Novu } from "@fern-api/novu";

export interface TriggerEventResponseDto {
    /** If trigger was acknowledged or not */
    acknowledged: boolean;
    status: Novu.TriggerEventResponseDtoStatus;
    /** In case of an error, this field will contain the error message */
    error?: string[];
    /** Transaction id for trigger */
    transactionId?: string;
}
