/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const CreateFeedRequestDto: core.serialization.ObjectSchema<
    serializers.CreateFeedRequestDto.Raw,
    Novu.CreateFeedRequestDto
> = core.serialization.object({
    name: core.serialization.string(),
});

export declare namespace CreateFeedRequestDto {
    interface Raw {
        name: string;
    }
}
