/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const FeedResponseDto: core.serialization.ObjectSchema<serializers.FeedResponseDto.Raw, Novu.FeedResponseDto> =
    core.serialization.object({
        id: core.serialization.property("_id", core.serialization.string().optional()),
        name: core.serialization.string(),
        identifier: core.serialization.string(),
        environmentId: core.serialization.property("_environmentId", core.serialization.string()),
        organizationId: core.serialization.property("_organizationId", core.serialization.string()),
    });

export declare namespace FeedResponseDto {
    interface Raw {
        _id?: string | null;
        name: string;
        identifier: string;
        _environmentId: string;
        _organizationId: string;
    }
}
