/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const ApiKey: core.serialization.ObjectSchema<serializers.ApiKey.Raw, Novu.ApiKey> = core.serialization.object({
    key: core.serialization.string(),
    userId: core.serialization.property("_userId", core.serialization.string()),
});

export declare namespace ApiKey {
    interface Raw {
        key: string;
        _userId: string;
    }
}
