/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const CreateEnvironmentRequestDto: core.serialization.ObjectSchema<
    serializers.CreateEnvironmentRequestDto.Raw,
    Novu.CreateEnvironmentRequestDto
> = core.serialization.object({
    name: core.serialization.string(),
    parentId: core.serialization.string().optional(),
});

export declare namespace CreateEnvironmentRequestDto {
    interface Raw {
        name: string;
        parentId?: string | null;
    }
}
