/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const DnsProperties: core.serialization.ObjectSchema<serializers.DnsProperties.Raw, Novu.DnsProperties> =
    core.serialization.object({
        inboundParseDomain: core.serialization.string().optional(),
    });

export declare namespace DnsProperties {
    interface Raw {
        inboundParseDomain?: string | null;
    }
}
