/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const EnvironmentResponseDto: core.serialization.ObjectSchema<
    serializers.EnvironmentResponseDto.Raw,
    Novu.EnvironmentResponseDto
> = core.serialization.object({
    id: core.serialization.property("_id", core.serialization.string().optional()),
    name: core.serialization.string(),
    organizationId: core.serialization.property("_organizationId", core.serialization.string()),
    identifier: core.serialization.string(),
    apiKeys: core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).ApiKey)),
    widget: core.serialization.lazyObject(async () => (await import("../../..")).WidgetSettings),
    parentId: core.serialization.property("_parentId", core.serialization.string()),
});

export declare namespace EnvironmentResponseDto {
    interface Raw {
        _id?: string | null;
        name: string;
        _organizationId: string;
        identifier: string;
        apiKeys: serializers.ApiKey.Raw[];
        widget: serializers.WidgetSettings.Raw;
        _parentId: string;
    }
}
