/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const UpdateWidgetSettingsRequestDto: core.serialization.ObjectSchema<
    serializers.UpdateWidgetSettingsRequestDto.Raw,
    Novu.UpdateWidgetSettingsRequestDto
> = core.serialization.object({
    notificationCenterEncryption: core.serialization.boolean(),
});

export declare namespace UpdateWidgetSettingsRequestDto {
    interface Raw {
        notificationCenterEncryption: boolean;
    }
}
