/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const UpdateEnvironmentRequestDto: core.serialization.ObjectSchema<
    serializers.UpdateEnvironmentRequestDto.Raw,
    Novu.UpdateEnvironmentRequestDto
> = core.serialization.object({
    name: core.serialization.string().optional(),
    identifier: core.serialization.string().optional(),
    parentId: core.serialization.string().optional(),
    dns: core.serialization.lazyObject(async () => (await import("../../..")).DnsProperties),
});

export declare namespace UpdateEnvironmentRequestDto {
    interface Raw {
        name?: string | null;
        identifier?: string | null;
        parentId?: string | null;
        dns: serializers.DnsProperties.Raw;
    }
}
