/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const WidgetSettings: core.serialization.ObjectSchema<serializers.WidgetSettings.Raw, Novu.WidgetSettings> =
    core.serialization.object({
        notificationCenterEncryption: core.serialization.boolean(),
    });

export declare namespace WidgetSettings {
    interface Raw {
        notificationCenterEncryption: boolean;
    }
}
