/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const CreateNotificationGroupRequestDto: core.serialization.ObjectSchema<
    serializers.CreateNotificationGroupRequestDto.Raw,
    Novu.CreateNotificationGroupRequestDto
> = core.serialization.object({
    name: core.serialization.string(),
});

export declare namespace CreateNotificationGroupRequestDto {
    interface Raw {
        name: string;
    }
}
