/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Novu } from "@fern-api/novu";

export interface ExecutionDetailsResponseDto {
    id?: string;
    organizationId: string;
    jobId: string;
    environmentId: string;
    notificationId: string;
    notificationTemplateId: string;
    subscriberId: string;
    messageId?: string;
    providerId?: string;
    transactionId: string;
    channel?: Novu.ExecutionDetailsResponseDtoChannel;
    detail: string;
    source: Novu.ExecutionDetailsResponseDtoSource;
    status: Novu.ExecutionDetailsResponseDtoStatus;
    isTest: boolean;
    isRetry: boolean;
    createdAt?: string;
}
