/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AddSubscribersRequestDto {
    /** List of subscriber identifiers that will be associated to the topic */
    subscribers: string[];
}
