/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateTopicRequestDto {
    /** User defined custom key and provided by the user that will be an unique identifier for the Topic created. */
    key: string;
    /** User defined custom name and provided by the user that will name the Topic created. */
    name: string;
}
