/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetTopicResponseDto {
    id?: string;
    organizationId: string;
    environmentId: string;
    key: string;
    name: string;
    subscribers: string[];
}
