/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RemoveSubscribersRequestDto {
    /** List of subscriber identifiers that will be removed to the topic */
    subscribers: string[];
}
