/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RenameTopicRequestDto {
    /** User defined custom name and provided by the user to rename the topic. */
    name: string;
}
