/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<serializers.changes.getCount.Response.Raw, number> =
    core.serialization.number();

export declare namespace Response {
    type Raw = number;
}
