/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import { Novu } from "@fern-api/novu";
import * as core from "../../core";

export const TopicPayloadDto: core.serialization.ObjectSchema<serializers.TopicPayloadDto.Raw, Novu.TopicPayloadDto> =
    core.serialization.object({
        topicKey: core.serialization.string(),
        type: core.serialization.lazy(async () => (await import("..")).TopicPayloadDtoType),
    });

export declare namespace TopicPayloadDto {
    interface Raw {
        topicKey: string;
        type: serializers.TopicPayloadDtoType.Raw;
    }
}
