/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import { Novu } from "@fern-api/novu";
import * as core from "../../core";

export const TriggerEventResponseDto: core.serialization.ObjectSchema<
    serializers.TriggerEventResponseDto.Raw,
    Novu.TriggerEventResponseDto
> = core.serialization.object({
    acknowledged: core.serialization.boolean(),
    status: core.serialization.lazy(async () => (await import("..")).TriggerEventResponseDtoStatus),
    error: core.serialization.list(core.serialization.string()).optional(),
    transactionId: core.serialization.string().optional(),
});

export declare namespace TriggerEventResponseDto {
    interface Raw {
        acknowledged: boolean;
        status: serializers.TriggerEventResponseDtoStatus.Raw;
        error?: string[] | null;
        transactionId?: string | null;
    }
}
