/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import { Novu } from "@fern-api/novu";
import * as core from "../../core";

export const TriggerEventRequestDtoTo: core.serialization.Schema<
    serializers.TriggerEventRequestDtoTo.Raw,
    Novu.TriggerEventRequestDtoTo
> = core.serialization.any();

export declare namespace TriggerEventRequestDtoTo {
    type Raw = unknown;
}
