/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import { Novu } from "@fern-api/novu";
import * as core from "../../core";

export const TriggerEventToAllRequestDto: core.serialization.ObjectSchema<
    serializers.TriggerEventToAllRequestDto.Raw,
    Novu.TriggerEventToAllRequestDto
> = core.serialization.object({
    name: core.serialization.string(),
    payload: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    overrides: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    transactionId: core.serialization.string().optional(),
    actor: core.serialization.lazy(async () => (await import("..")).TriggerEventToAllRequestDtoActor).optional(),
});

export declare namespace TriggerEventToAllRequestDto {
    interface Raw {
        name: string;
        payload: Record<string, unknown>;
        overrides?: Record<string, unknown> | null;
        transactionId?: string | null;
        actor?: (serializers.TriggerEventToAllRequestDtoActor.Raw | undefined) | null;
    }
}
