/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Novu } from "@fern-api/novu";
import urlJoin from "url-join";
import * as core from "../../../../core";
import * as serializers from "../../../../serialization";
import * as errors from "../../../../errors";

export declare namespace Feeds {
    interface Options {
        environment: string;
    }
}

export class Feeds {
    constructor(private readonly options: Feeds.Options) {}

    public async feedsControllerGetFeeds(): Promise<Novu.FeedResponseDto[]> {
        const _response = await core.fetcher({
            url: urlJoin(this.options.environment, "/v1/feeds"),
            method: "GET",
        });
        if (_response.ok) {
            return await serializers.feeds.feedsControllerGetFeeds.Response.parseOrThrow(
                _response.body as serializers.feeds.feedsControllerGetFeeds.Response.Raw,
                { allowUnknownKeys: true }
            );
        }

        if (_response.error.reason === "status-code") {
            throw new errors.NovuError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.NovuError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.NovuTimeoutError();
            case "unknown":
                throw new errors.NovuError({
                    message: _response.error.errorMessage,
                });
        }
    }

    public async feedsControllerCreateFeed(request: Novu.CreateFeedRequestDto): Promise<void> {
        const _response = await core.fetcher({
            url: urlJoin(this.options.environment, "/v1/feeds"),
            method: "POST",
            body: await serializers.CreateFeedRequestDto.jsonOrThrow(request),
        });
        if (_response.ok) {
            return;
        }

        if (_response.error.reason === "status-code") {
            throw new errors.NovuError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.NovuError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.NovuTimeoutError();
            case "unknown":
                throw new errors.NovuError({
                    message: _response.error.errorMessage,
                });
        }
    }

    public async feedsControllerDeleteFeedById(feedId: string): Promise<Novu.FeedResponseDto[]> {
        const _response = await core.fetcher({
            url: urlJoin(this.options.environment, `/v1/feeds/${feedId}`),
            method: "DELETE",
        });
        if (_response.ok) {
            return await serializers.feeds.feedsControllerDeleteFeedById.Response.parseOrThrow(
                _response.body as serializers.feeds.feedsControllerDeleteFeedById.Response.Raw,
                { allowUnknownKeys: true }
            );
        }

        if (_response.error.reason === "status-code") {
            throw new errors.NovuError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.NovuError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.NovuTimeoutError();
            case "unknown":
                throw new errors.NovuError({
                    message: _response.error.errorMessage,
                });
        }
    }
}
