/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Novu } from "@fern-api/novu";

export interface CreateNotificationTemplateRequestDto {
    name: string;
    notificationGroupId: string;
    tags?: string[];
    description?: string;
    steps: Novu.NotificationChannel[];
    active?: boolean;
    draft?: boolean;
    critical?: boolean;
    preferenceSettings?: Novu.PreferenceChannels;
}
