/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Novu } from "@fern-api/novu";

export interface UpdateNotificationTemplateRequestDto {
    name: string;
    tags?: string[];
    description?: string;
    identifier?: string;
    steps?: Novu.NotificationStep[];
    notificationGroupId: string;
    active?: boolean;
    critical?: boolean;
    preferenceSettings?: Novu.PreferenceChannels;
}
