/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Novu } from "@fern-api/novu";

export interface UpdateEnvironmentRequestDto {
    name?: string;
    identifier?: string;
    parentId?: string;
    dns: Novu.DnsProperties;
}
