/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface FeedResponseDto {
    id?: string;
    name: string;
    identifier: string;
    environmentId: string;
    organizationId: string;
}
