/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const CreateNotificationTemplateRequestDto: core.serialization.ObjectSchema<
    serializers.CreateNotificationTemplateRequestDto.Raw,
    Novu.CreateNotificationTemplateRequestDto
> = core.serialization.object({
    name: core.serialization.string(),
    notificationGroupId: core.serialization.string(),
    tags: core.serialization.list(core.serialization.string()).optional(),
    description: core.serialization.string().optional(),
    steps: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("../../..")).NotificationChannel)
    ),
    active: core.serialization.boolean().optional(),
    draft: core.serialization.boolean().optional(),
    critical: core.serialization.boolean().optional(),
    preferenceSettings: core.serialization
        .lazyObject(async () => (await import("../../..")).PreferenceChannels)
        .optional(),
});

export declare namespace CreateNotificationTemplateRequestDto {
    interface Raw {
        name: string;
        notificationGroupId: string;
        tags?: string[] | null;
        description?: string | null;
        steps: serializers.NotificationChannel.Raw[];
        active?: boolean | null;
        draft?: boolean | null;
        critical?: boolean | null;
        preferenceSettings?: serializers.PreferenceChannels.Raw | null;
    }
}
