/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const NotificationChannel: core.serialization.ObjectSchema<
    serializers.NotificationChannel.Raw,
    Novu.NotificationChannel
> = core.serialization.object({
    template: core.serialization.lazyObject(async () => (await import("../../..")).MessageTemplate).optional(),
    filters: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).StepFilter))
        .optional(),
    active: core.serialization.boolean().optional(),
});

export declare namespace NotificationChannel {
    interface Raw {
        template?: serializers.MessageTemplate.Raw | null;
        filters?: serializers.StepFilter.Raw[] | null;
        active?: boolean | null;
    }
}
