/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const UpdateNotificationTemplateRequestDto: core.serialization.ObjectSchema<
    serializers.UpdateNotificationTemplateRequestDto.Raw,
    Novu.UpdateNotificationTemplateRequestDto
> = core.serialization.object({
    name: core.serialization.string(),
    tags: core.serialization.list(core.serialization.string()).optional(),
    description: core.serialization.string().optional(),
    identifier: core.serialization.string().optional(),
    steps: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).NotificationStep))
        .optional(),
    notificationGroupId: core.serialization.string(),
    active: core.serialization.boolean().optional(),
    critical: core.serialization.boolean().optional(),
    preferenceSettings: core.serialization
        .lazyObject(async () => (await import("../../..")).PreferenceChannels)
        .optional(),
});

export declare namespace UpdateNotificationTemplateRequestDto {
    interface Raw {
        name: string;
        tags?: string[] | null;
        description?: string | null;
        identifier?: string | null;
        steps?: serializers.NotificationStep.Raw[] | null;
        notificationGroupId: string;
        active?: boolean | null;
        critical?: boolean | null;
        preferenceSettings?: serializers.PreferenceChannels.Raw | null;
    }
}
