/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SubscribersControllerGetSubscribersRequest {
    /**
     * The page to fetch, defaults to 0
     */
    page?: number;
}
