/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface NotificationsControllerGetNotificationsRequest {
    search: string;
    page?: number;
    transactionId?: string;
}
