/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const ChannelCredentials: core.serialization.ObjectSchema<
    serializers.ChannelCredentials.Raw,
    Novu.ChannelCredentials
> = core.serialization.object({
    webhookUrl: core.serialization.string(),
    deviceTokens: core.serialization.list(core.serialization.string()).optional(),
});

export declare namespace ChannelCredentials {
    interface Raw {
        webhookUrl: string;
        deviceTokens?: string[] | null;
    }
}
