/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const ChannelSettings: core.serialization.ObjectSchema<serializers.ChannelSettings.Raw, Novu.ChannelSettings> =
    core.serialization.object({
        integrationId: core.serialization.property("_integrationId", core.serialization.string()),
        providerId: core.serialization.lazy(async () => (await import("../../..")).ChannelSettingsProviderId),
        credentials: core.serialization.lazyObject(async () => (await import("../../..")).ChannelSettingsCredentials),
    });

export declare namespace ChannelSettings {
    interface Raw {
        _integrationId: string;
        providerId: serializers.ChannelSettingsProviderId.Raw;
        credentials: serializers.ChannelSettingsCredentials.Raw;
    }
}
