/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const DeleteSubscriberResponseDto: core.serialization.ObjectSchema<
    serializers.DeleteSubscriberResponseDto.Raw,
    Novu.DeleteSubscriberResponseDto
> = core.serialization.object({
    acknowledged: core.serialization.boolean(),
    status: core.serialization.lazy(async () => (await import("../../..")).DeleteSubscriberResponseDtoStatus),
});

export declare namespace DeleteSubscriberResponseDto {
    interface Raw {
        acknowledged: boolean;
        status: serializers.DeleteSubscriberResponseDtoStatus.Raw;
    }
}
