/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const EmailBlockStylesTextAlign: core.serialization.Schema<
    serializers.EmailBlockStylesTextAlign.Raw,
    Novu.EmailBlockStylesTextAlign
> = core.serialization.enum_(["left", "right", "center"]);

export declare namespace EmailBlockStylesTextAlign {
    type Raw = "left" | "right" | "center";
}
