/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const EmailBlockStyles: core.serialization.ObjectSchema<
    serializers.EmailBlockStyles.Raw,
    Novu.EmailBlockStyles
> = core.serialization.object({
    textAlign: core.serialization.lazy(async () => (await import("../../..")).EmailBlockStylesTextAlign).optional(),
});

export declare namespace EmailBlockStyles {
    interface Raw {
        textAlign?: serializers.EmailBlockStylesTextAlign.Raw | null;
    }
}
