/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const EmailBlockType: core.serialization.Schema<serializers.EmailBlockType.Raw, Novu.EmailBlockType> =
    core.serialization.enum_(["text", "button"]);

export declare namespace EmailBlockType {
    type Raw = "text" | "button";
}
