/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const MarkMessageAsRequestDto: core.serialization.ObjectSchema<
    serializers.MarkMessageAsRequestDto.Raw,
    Novu.MarkMessageAsRequestDto
> = core.serialization.object({
    messageId: core.serialization.lazy(async () => (await import("../../..")).MarkMessageAsRequestDtoMessageId),
    mark: core.serialization.lazyObject(async () => (await import("../../..")).MarkMessageFields),
});

export declare namespace MarkMessageAsRequestDto {
    interface Raw {
        messageId?: serializers.MarkMessageAsRequestDtoMessageId.Raw;
        mark: serializers.MarkMessageFields.Raw;
    }
}
