/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const MarkMessageAsRequestDtoMessageId: core.serialization.Schema<
    serializers.MarkMessageAsRequestDtoMessageId.Raw,
    Novu.MarkMessageAsRequestDtoMessageId
> = core.serialization.unknown();

export declare namespace MarkMessageAsRequestDtoMessageId {
    type Raw = unknown;
}
