/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const MessageCta: core.serialization.ObjectSchema<serializers.MessageCta.Raw, Novu.MessageCta> =
    core.serialization.object({
        type: core.serialization.lazy(async () => (await import("../../..")).MessageCtaType),
        data: core.serialization.lazyObject(async () => (await import("../../..")).MessageCtaData),
        action: core.serialization.lazyObject(async () => (await import("../../..")).MessageAction).optional(),
    });

export declare namespace MessageCta {
    interface Raw {
        type: serializers.MessageCtaType.Raw;
        data: serializers.MessageCtaData.Raw;
        action?: serializers.MessageAction.Raw | null;
    }
}
