/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const MessageCtaData: core.serialization.ObjectSchema<serializers.MessageCtaData.Raw, Novu.MessageCtaData> =
    core.serialization.object({
        url: core.serialization.string().optional(),
    });

export declare namespace MessageCtaData {
    interface Raw {
        url?: string | null;
    }
}
