/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const MessageActionType: core.serialization.Schema<serializers.MessageActionType.Raw, Novu.MessageActionType> =
    core.serialization.enum_(["pending", "done"]);

export declare namespace MessageActionType {
    type Raw = "pending" | "done";
}
