/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const MessageCtaType: core.serialization.Schema<serializers.MessageCtaType.Raw, Novu.MessageCtaType> =
    core.serialization.enum_(["redirect"]);

export declare namespace MessageCtaType {
    type Raw = "redirect";
}
