/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const MessageResponseDtoContent: core.serialization.Schema<
    serializers.MessageResponseDtoContent.Raw,
    Novu.MessageResponseDtoContent
> = core.serialization.unknown();

export declare namespace MessageResponseDtoContent {
    type Raw = unknown;
}
