/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const MessageResponseDtoChannel: core.serialization.Schema<
    serializers.MessageResponseDtoChannel.Raw,
    Novu.MessageResponseDtoChannel
> = core.serialization.enum_(["in_app", "email", "sms", "chat", "push"]);

export declare namespace MessageResponseDtoChannel {
    type Raw = "in_app" | "email" | "sms" | "chat" | "push";
}
