/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const MessageAction: core.serialization.ObjectSchema<serializers.MessageAction.Raw, Novu.MessageAction> =
    core.serialization.object({
        status: core.serialization.lazy(async () => (await import("../../..")).MessageActionType).optional(),
        buttons: core.serialization.unknown().optional(),
        result: core.serialization.lazyObject(async () => (await import("../../..")).MessageActionResult),
    });

export declare namespace MessageAction {
    interface Raw {
        status?: serializers.MessageActionType.Raw | null;
        buttons?: unknown | null;
        result: serializers.MessageActionResult.Raw;
    }
}
