/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const MessageResponseDtoStatus: core.serialization.Schema<
    serializers.MessageResponseDtoStatus.Raw,
    Novu.MessageResponseDtoStatus
> = core.serialization.enum_(["sent", "error", "warning"]);

export declare namespace MessageResponseDtoStatus {
    type Raw = "sent" | "error" | "warning";
}
