/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const SubscriberResponseDto: core.serialization.ObjectSchema<
    serializers.SubscriberResponseDto.Raw,
    Novu.SubscriberResponseDto
> = core.serialization.object({
    id: core.serialization.property("_id", core.serialization.string().optional()),
    firstName: core.serialization.string(),
    lastName: core.serialization.string(),
    email: core.serialization.string(),
    phone: core.serialization.string().optional(),
    avatar: core.serialization.string().optional(),
    locale: core.serialization.string().optional(),
    subscriberId: core.serialization.string(),
    channels: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).ChannelSettings))
        .optional(),
    isOnline: core.serialization.boolean().optional(),
    lastOnlineAt: core.serialization.string().optional(),
    organizationId: core.serialization.property("_organizationId", core.serialization.string()),
    environmentId: core.serialization.property("_environmentId", core.serialization.string()),
    deleted: core.serialization.boolean(),
    createdAt: core.serialization.string(),
    updatedAt: core.serialization.string(),
    v: core.serialization.property("__v", core.serialization.number().optional()),
});

export declare namespace SubscriberResponseDto {
    interface Raw {
        _id?: string | null;
        firstName: string;
        lastName: string;
        email: string;
        phone?: string | null;
        avatar?: string | null;
        locale?: string | null;
        subscriberId: string;
        channels?: serializers.ChannelSettings.Raw[] | null;
        isOnline?: boolean | null;
        lastOnlineAt?: string | null;
        _organizationId: string;
        _environmentId: string;
        deleted: boolean;
        createdAt: string;
        updatedAt: string;
        __v?: number | null;
    }
}
