/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const SubscribersResponseDto: core.serialization.ObjectSchema<
    serializers.SubscribersResponseDto.Raw,
    Novu.SubscribersResponseDto
> = core.serialization.object({
    page: core.serialization.number(),
    totalCount: core.serialization.number(),
    pageSize: core.serialization.number(),
    data: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("../../..")).SubscriberResponseDto)
    ),
});

export declare namespace SubscribersResponseDto {
    interface Raw {
        page: number;
        totalCount: number;
        pageSize: number;
        data: serializers.SubscriberResponseDto.Raw[];
    }
}
