/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const UnseenCountResponse: core.serialization.ObjectSchema<
    serializers.UnseenCountResponse.Raw,
    Novu.UnseenCountResponse
> = core.serialization.object({
    count: core.serialization.number(),
});

export declare namespace UnseenCountResponse {
    interface Raw {
        count: number;
    }
}
