/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const UpdateSubscriberChannelRequestDto: core.serialization.ObjectSchema<
    serializers.UpdateSubscriberChannelRequestDto.Raw,
    Novu.UpdateSubscriberChannelRequestDto
> = core.serialization.object({
    providerId: core.serialization.lazy(
        async () => (await import("../../..")).UpdateSubscriberChannelRequestDtoProviderId
    ),
    credentials: core.serialization.lazyObject(
        async () => (await import("../../..")).UpdateSubscriberChannelRequestDtoCredentials
    ),
});

export declare namespace UpdateSubscriberChannelRequestDto {
    interface Raw {
        providerId: serializers.UpdateSubscriberChannelRequestDtoProviderId.Raw;
        credentials: serializers.UpdateSubscriberChannelRequestDtoCredentials.Raw;
    }
}
