/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const UpdateSubscriberPreferenceResponseDtoTemplate: core.serialization.ObjectSchema<
    serializers.UpdateSubscriberPreferenceResponseDtoTemplate.Raw,
    Novu.UpdateSubscriberPreferenceResponseDtoTemplate
> = core.serialization
    .object({})
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).TemplateResponse));

export declare namespace UpdateSubscriberPreferenceResponseDtoTemplate {
    interface Raw extends serializers.TemplateResponse.Raw {}
}
