/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const UpdateSubscriberPreferenceResponseDto: core.serialization.ObjectSchema<
    serializers.UpdateSubscriberPreferenceResponseDto.Raw,
    Novu.UpdateSubscriberPreferenceResponseDto
> = core.serialization.object({
    template: core.serialization.lazyObject(
        async () => (await import("../../..")).UpdateSubscriberPreferenceResponseDtoTemplate
    ),
    preference: core.serialization.lazyObject(
        async () => (await import("../../..")).UpdateSubscriberPreferenceResponseDtoPreference
    ),
});

export declare namespace UpdateSubscriberPreferenceResponseDto {
    interface Raw {
        template: serializers.UpdateSubscriberPreferenceResponseDtoTemplate.Raw;
        preference: serializers.UpdateSubscriberPreferenceResponseDtoPreference.Raw;
    }
}
