/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const UpdateSubscriberChannelRequestDtoProviderId: core.serialization.Schema<
    serializers.UpdateSubscriberChannelRequestDtoProviderId.Raw,
    Novu.UpdateSubscriberChannelRequestDtoProviderId
> = core.serialization.enum_(["slack", "discord", "msteams", "fcm", "apns", "expo"]);

export declare namespace UpdateSubscriberChannelRequestDtoProviderId {
    type Raw = "slack" | "discord" | "msteams" | "fcm" | "apns" | "expo";
}
