/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const UpdateSubscriberOnlineFlagRequestDto: core.serialization.ObjectSchema<
    serializers.UpdateSubscriberOnlineFlagRequestDto.Raw,
    Novu.UpdateSubscriberOnlineFlagRequestDto
> = core.serialization.object({
    isOnline: core.serialization.boolean(),
});

export declare namespace UpdateSubscriberOnlineFlagRequestDto {
    interface Raw {
        isOnline: boolean;
    }
}
