/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const UpdateSubscriberPreferenceResponseDtoPreference: core.serialization.ObjectSchema<
    serializers.UpdateSubscriberPreferenceResponseDtoPreference.Raw,
    Novu.UpdateSubscriberPreferenceResponseDtoPreference
> = core.serialization
    .object({})
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).Preference));

export declare namespace UpdateSubscriberPreferenceResponseDtoPreference {
    interface Raw extends serializers.Preference.Raw {}
}
