/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Novu } from "@fern-api/novu";

export interface ActivityNotificationResponseDto {
    id?: string;
    environmentId: string;
    organizationId: string;
    transactionId: string;
    createdAt?: string;
    channels?: Novu.ActivityNotificationResponseDtoChannels;
    subscriber?: Novu.ActivityNotificationSubscriberResponseDto;
    template?: Novu.ActivityNotificationTemplateResponseDto;
    jobs?: Novu.ActivityNotificationJobResponseDto[];
}
