/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Novu } from "@fern-api/novu";

export interface ActivitiesResponseDto {
    totalCount: number;
    data: Novu.ActivityNotificationResponseDto[];
    pageSize: number;
    page: number;
}
