/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ActivityNotificationSubscriberResponseDto {
    firstName?: string;
    id: string;
    lastName?: string;
    email?: string;
    phone?: string;
}
