/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Novu } from "@fern-api/novu";

export interface ActivityNotificationStepResponseDto {
    id: string;
    active: boolean;
    filters: Novu.StepFilter;
    template?: Novu.MessageTemplateDto;
}
