/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ActivityNotificationExecutionDetailResponseDtoSource = "Credentials" | "Internal" | "Payload" | "Webhook";

export const ActivityNotificationExecutionDetailResponseDtoSource = {
    Credentials: "Credentials",
    Internal: "Internal",
    Payload: "Payload",
    Webhook: "Webhook",
} as const;
