/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Novu } from "@fern-api/novu";

export interface ActivityNotificationExecutionDetailResponseDto {
    id: string;
    jobId: string;
    status: Novu.ActivityNotificationExecutionDetailResponseDtoStatus;
    detail: string;
    isRetry: boolean;
    isTest: boolean;
    providerId: Record<string, unknown>;
    raw?: string;
    source: Novu.ActivityNotificationExecutionDetailResponseDtoSource;
}
