/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Novu } from "@fern-api/novu";

export interface ActivityNotificationJobResponseDto {
    id: string;
    type: string;
    digest?: Record<string, unknown>;
    executionDetails: Novu.ActivityNotificationExecutionDetailResponseDto[];
    step: Novu.ActivityNotificationStepResponseDto;
    payload?: Record<string, unknown>;
    providerId: Record<string, unknown>;
    status: string;
}
