/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of channel that is enabled or not
 */
export type ChannelPreferenceType = "in_app" | "email" | "sms" | "chat" | "push";

export const ChannelPreferenceType = {
    InApp: "in_app",
    Email: "email",
    Sms: "sms",
    Chat: "chat",
    Push: "push",
} as const;
