/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type FieldFilterPartOperator =
    | "LARGER"
    | "SMALLER"
    | "LARGER_EQUAL"
    | "SMALLER_EQUAL"
    | "EQUAL"
    | "NOT_EQUAL"
    | "ALL_IN"
    | "ANY_IN"
    | "NOT_IN"
    | "BETWEEN"
    | "NOT_BETWEEN"
    | "LIKE"
    | "NOT_LIKE"
    | "IN";

export const FieldFilterPartOperator = {
    Larger: "LARGER",
    Smaller: "SMALLER",
    LargerEqual: "LARGER_EQUAL",
    SmallerEqual: "SMALLER_EQUAL",
    Equal: "EQUAL",
    NotEqual: "NOT_EQUAL",
    AllIn: "ALL_IN",
    AnyIn: "ANY_IN",
    NotIn: "NOT_IN",
    Between: "BETWEEN",
    NotBetween: "NOT_BETWEEN",
    Like: "LIKE",
    NotLike: "NOT_LIKE",
    In: "IN",
} as const;
