/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type FieldFilterPartOn = "subscriber" | "payload";

export const FieldFilterPartOn = {
    Subscriber: "subscriber",
    Payload: "payload",
} as const;
