/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type NotificationStepMetadataType = "regular" | "backoff" | "scheduled";

export const NotificationStepMetadataType = {
    Regular: "regular",
    Backoff: "backoff",
    Scheduled: "scheduled",
} as const;
