/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type NotificationStepMetadataBackofUnit = "seconds" | "minutes" | "hours" | "days";

export const NotificationStepMetadataBackofUnit = {
    Seconds: "seconds",
    Minutes: "minutes",
    Hours: "hours",
    Days: "days",
} as const;
