/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Novu } from "@fern-api/novu";

export interface NotificationTemplateResponse {
    id?: string;
    name: string;
    description: string;
    active: boolean;
    draft: boolean;
    preferenceSettings: Novu.PreferenceChannels;
    critical: boolean;
    tags: string[];
    steps: Novu.NotificationStep[];
    organizationId: string;
    creatorId: string;
    environmentId: string;
    triggers: Novu.NotificationTrigger[];
    notificationGroupId: string;
    parentId?: string;
    deleted: boolean;
    deletedAt: string;
    deletedBy: string;
    notificationGroup?: Novu.NotificationGroup;
}
