/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface NotificationGroup {
    id?: string;
    name: string;
    environmentId: string;
    organizationId: string;
    parentId?: string;
}
