/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Novu } from "@fern-api/novu";

export interface NotificationStep {
    id?: string;
    templateId?: string;
    active?: boolean;
    shouldStopOnFail?: boolean;
    template?: Novu.MessageTemplate;
    filters?: Novu.StepFilter[];
    parentId?: string;
    metadata?: Novu.NotificationStepMetadata;
    replyCallback?: Record<string, unknown>;
}
