/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Novu } from "@fern-api/novu";

export interface NotificationTrigger {
    type: string;
    identifier: string;
    variables: Novu.NotificationTriggerVariable[];
    subscriberVariables?: Novu.NotificationTriggerVariable[];
}
