/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Novu } from "@fern-api/novu";

export interface StepFilter {
    isNegated: boolean;
    type: Novu.StepFilterType;
    value: Novu.StepFilterValue;
    children: Novu.FieldFilterPart[];
}
