/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type StepFilterType = "BOOLEAN" | "TEXT" | "DATE" | "NUMBER" | "STATEMENT" | "LIST" | "MULTI_LIST" | "GROUP";

export const StepFilterType = {
    Boolean: "BOOLEAN",
    Text: "TEXT",
    Date: "DATE",
    Number: "NUMBER",
    Statement: "STATEMENT",
    List: "LIST",
    MultiList: "MULTI_LIST",
    Group: "GROUP",
} as const;
