/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { InboundParse } from "./api/resources/inboundParse/client/Client";
import { Environments } from "./api/resources/environments/client/Client";
import { NotificationGroups } from "./api/resources/notificationGroups/client/Client";
import { Changes } from "./api/resources/changes/client/Client";
import { Layouts } from "./api/resources/layouts/client/Client";
import { ExecutionDetails } from "./api/resources/executionDetails/client/Client";
import { NotificationTemplates } from "./api/resources/notificationTemplates/client/Client";
import { Integrations } from "./api/resources/integrations/client/Client";
import { Events } from "./api/resources/events/client/Client";
import { Subscribers } from "./api/resources/subscribers/client/Client";
import { Topics } from "./api/resources/topics/client/Client";
import { Activity } from "./api/resources/activity/client/Client";
import { Notification } from "./api/resources/notification/client/Client";
import { Feeds } from "./api/resources/feeds/client/Client";
import { Messages } from "./api/resources/messages/client/Client";

export declare namespace NovuClient {
    interface Options {
        environment: environments.NovuEnvironment | string;
        apiKey?: core.Supplier<string>;
    }
}

export class NovuClient {
    constructor(private readonly options: NovuClient.Options) {}

    private _inboundParse: InboundParse | undefined;

    public get inboundParse(): InboundParse {
        return (this._inboundParse ??= new InboundParse(this.options));
    }

    private _environments: Environments | undefined;

    public get environments(): Environments {
        return (this._environments ??= new Environments(this.options));
    }

    private _notificationGroups: NotificationGroups | undefined;

    public get notificationGroups(): NotificationGroups {
        return (this._notificationGroups ??= new NotificationGroups(this.options));
    }

    private _changes: Changes | undefined;

    public get changes(): Changes {
        return (this._changes ??= new Changes(this.options));
    }

    private _layouts: Layouts | undefined;

    public get layouts(): Layouts {
        return (this._layouts ??= new Layouts(this.options));
    }

    private _executionDetails: ExecutionDetails | undefined;

    public get executionDetails(): ExecutionDetails {
        return (this._executionDetails ??= new ExecutionDetails(this.options));
    }

    private _notificationTemplates: NotificationTemplates | undefined;

    public get notificationTemplates(): NotificationTemplates {
        return (this._notificationTemplates ??= new NotificationTemplates(this.options));
    }

    private _integrations: Integrations | undefined;

    public get integrations(): Integrations {
        return (this._integrations ??= new Integrations(this.options));
    }

    private _events: Events | undefined;

    public get events(): Events {
        return (this._events ??= new Events(this.options));
    }

    private _subscribers: Subscribers | undefined;

    public get subscribers(): Subscribers {
        return (this._subscribers ??= new Subscribers(this.options));
    }

    private _topics: Topics | undefined;

    public get topics(): Topics {
        return (this._topics ??= new Topics(this.options));
    }

    private _activity: Activity | undefined;

    public get activity(): Activity {
        return (this._activity ??= new Activity(this.options));
    }

    private _notification: Notification | undefined;

    public get notification(): Notification {
        return (this._notification ??= new Notification(this.options));
    }

    private _feeds: Feeds | undefined;

    public get feeds(): Feeds {
        return (this._feeds ??= new Feeds(this.options));
    }

    private _messages: Messages | undefined;

    public get messages(): Messages {
        return (this._messages ??= new Messages(this.options));
    }
}
