/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const NovuEnvironment = {
    Production: "https://api.novu.co/v1",
} as const;

export type NovuEnvironment = typeof NovuEnvironment.Production;
