/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Novu } from "@fern-api/novu";

export interface CreateIntegrationRequestDto {
    providerId: string;
    channel: Novu.CreateEnvironmentRequestDtoChannel;
    credentials: Novu.CredentialsDto;
    active: boolean;
    check: boolean;
}
