/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CredentialsDto {
    apiKey?: string;
    user?: string;
    secretKey?: string;
    domain?: string;
    password?: string;
    host?: string;
    port?: string;
    secure?: boolean;
    region?: string;
    accountSid?: string;
    messageProfileId?: string;
    token?: string;
    from?: string;
    senderName?: string;
    projectName?: string;
    applicationId?: string;
    clientId?: string;
}
