/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Novu } from "@fern-api/novu";

export interface IntegrationResponseDto {
    id?: string;
    environmentId: string;
    organizationId: string;
    providerId: string;
    channel: Novu.IntegrationResponseDtoChannelChannel;
    credentials: Novu.CredentialsDto;
    active: boolean;
    deleted: boolean;
    deletedAt: string;
    deletedBy: string;
}
