/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const GetMxRecordResponseDto: core.serialization.ObjectSchema<
    serializers.GetMxRecordResponseDto.Raw,
    Novu.GetMxRecordResponseDto
> = core.serialization.object({
    mxRecordConfigured: core.serialization.boolean(),
});

export declare namespace GetMxRecordResponseDto {
    interface Raw {
        mxRecordConfigured: boolean;
    }
}
