/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TopicsControllerFilterTopicsRequest {
    /**
     * Number of page for the pagination
     */
    page?: number;
    /**
     * Size of page for the pagination
     */
    pageSize?: number;
    /**
     * Topic key
     */
    key?: string;
}
