/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const ActivityNotificationExecutionDetailResponseDto: core.serialization.ObjectSchema<
    serializers.ActivityNotificationExecutionDetailResponseDto.Raw,
    Novu.ActivityNotificationExecutionDetailResponseDto
> = core.serialization.object({
    id: core.serialization.property("_id", core.serialization.string()),
    jobId: core.serialization.property("_jobId", core.serialization.string()),
    status: core.serialization.lazy(
        async () => (await import("../../..")).ActivityNotificationExecutionDetailResponseDtoStatus
    ),
    detail: core.serialization.string(),
    isRetry: core.serialization.boolean(),
    isTest: core.serialization.boolean(),
    providerId: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    raw: core.serialization.string().optional(),
    source: core.serialization.lazy(
        async () => (await import("../../..")).ActivityNotificationExecutionDetailResponseDtoSource
    ),
});

export declare namespace ActivityNotificationExecutionDetailResponseDto {
    interface Raw {
        _id: string;
        _jobId: string;
        status: serializers.ActivityNotificationExecutionDetailResponseDtoStatus.Raw;
        detail: string;
        isRetry: boolean;
        isTest: boolean;
        providerId: Record<string, unknown>;
        raw?: string | null;
        source: serializers.ActivityNotificationExecutionDetailResponseDtoSource.Raw;
    }
}
