/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const ActivityNotificationStepResponseDto: core.serialization.ObjectSchema<
    serializers.ActivityNotificationStepResponseDto.Raw,
    Novu.ActivityNotificationStepResponseDto
> = core.serialization.object({
    id: core.serialization.property("_id", core.serialization.string()),
    active: core.serialization.boolean(),
    filters: core.serialization.lazyObject(async () => (await import("../../..")).StepFilter),
    template: core.serialization.lazyObject(async () => (await import("../../..")).MessageTemplateDto).optional(),
});

export declare namespace ActivityNotificationStepResponseDto {
    interface Raw {
        _id: string;
        active: boolean;
        filters: serializers.StepFilter.Raw;
        template?: serializers.MessageTemplateDto.Raw | null;
    }
}
