/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const ActivityNotificationJobResponseDto: core.serialization.ObjectSchema<
    serializers.ActivityNotificationJobResponseDto.Raw,
    Novu.ActivityNotificationJobResponseDto
> = core.serialization.object({
    id: core.serialization.property("_id", core.serialization.string()),
    type: core.serialization.string(),
    digest: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    executionDetails: core.serialization.list(
        core.serialization.lazyObject(
            async () => (await import("../../..")).ActivityNotificationExecutionDetailResponseDto
        )
    ),
    step: core.serialization.lazyObject(async () => (await import("../../..")).ActivityNotificationStepResponseDto),
    payload: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    providerId: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    status: core.serialization.string(),
});

export declare namespace ActivityNotificationJobResponseDto {
    interface Raw {
        _id: string;
        type: string;
        digest?: Record<string, unknown> | null;
        executionDetails: serializers.ActivityNotificationExecutionDetailResponseDto.Raw[];
        step: serializers.ActivityNotificationStepResponseDto.Raw;
        payload?: Record<string, unknown> | null;
        providerId: Record<string, unknown>;
        status: string;
    }
}
