/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const ActivityStatsResponseDto: core.serialization.ObjectSchema<
    serializers.ActivityStatsResponseDto.Raw,
    Novu.ActivityStatsResponseDto
> = core.serialization.object({
    weeklySent: core.serialization.number(),
    monthlySent: core.serialization.number(),
    yearlySent: core.serialization.number(),
});

export declare namespace ActivityStatsResponseDto {
    interface Raw {
        weeklySent: number;
        monthlySent: number;
        yearlySent: number;
    }
}
