/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const ActivityNotificationSubscriberResponseDto: core.serialization.ObjectSchema<
    serializers.ActivityNotificationSubscriberResponseDto.Raw,
    Novu.ActivityNotificationSubscriberResponseDto
> = core.serialization.object({
    firstName: core.serialization.string().optional(),
    id: core.serialization.property("_id", core.serialization.string()),
    lastName: core.serialization.string().optional(),
    email: core.serialization.string().optional(),
    phone: core.serialization.string().optional(),
});

export declare namespace ActivityNotificationSubscriberResponseDto {
    interface Raw {
        firstName?: string | null;
        _id: string;
        lastName?: string | null;
        email?: string | null;
        phone?: string | null;
    }
}
