/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const ActivityNotificationTemplateResponseDto: core.serialization.ObjectSchema<
    serializers.ActivityNotificationTemplateResponseDto.Raw,
    Novu.ActivityNotificationTemplateResponseDto
> = core.serialization.object({
    id: core.serialization.property("_id", core.serialization.string().optional()),
    name: core.serialization.string(),
    triggers: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("../../..")).NotificationTrigger)
    ),
});

export declare namespace ActivityNotificationTemplateResponseDto {
    interface Raw {
        _id?: string | null;
        name: string;
        triggers: serializers.NotificationTrigger.Raw[];
    }
}
