/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const ActivityNotificationResponseDtoChannels: core.serialization.Schema<
    serializers.ActivityNotificationResponseDtoChannels.Raw,
    Novu.ActivityNotificationResponseDtoChannels
> = core.serialization.enum_(["in_app", "email", "sms", "chat", "push", "digest", "trigger", "delay"]);

export declare namespace ActivityNotificationResponseDtoChannels {
    type Raw = "in_app" | "email" | "sms" | "chat" | "push" | "digest" | "trigger" | "delay";
}
