/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const ActivityNotificationExecutionDetailResponseDtoStatus: core.serialization.Schema<
    serializers.ActivityNotificationExecutionDetailResponseDtoStatus.Raw,
    Novu.ActivityNotificationExecutionDetailResponseDtoStatus
> = core.serialization.enum_(["Success", "Warning", "Failed", "Pending", "Queued", "ReadConfirmation"]);

export declare namespace ActivityNotificationExecutionDetailResponseDtoStatus {
    type Raw = "Success" | "Warning" | "Failed" | "Pending" | "Queued" | "ReadConfirmation";
}
