/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const FieldFilterPart: core.serialization.ObjectSchema<serializers.FieldFilterPart.Raw, Novu.FieldFilterPart> =
    core.serialization.object({
        field: core.serialization.string(),
        value: core.serialization.string(),
        operator: core.serialization.lazy(async () => (await import("../../..")).FieldFilterPartOperator),
        on: core.serialization.lazy(async () => (await import("../../..")).FieldFilterPartOn),
    });

export declare namespace FieldFilterPart {
    interface Raw {
        field: string;
        value: string;
        operator: serializers.FieldFilterPartOperator.Raw;
        on: serializers.FieldFilterPartOn.Raw;
    }
}
