/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const FieldFilterPartOn: core.serialization.Schema<serializers.FieldFilterPartOn.Raw, Novu.FieldFilterPartOn> =
    core.serialization.enum_(["subscriber", "payload"]);

export declare namespace FieldFilterPartOn {
    type Raw = "subscriber" | "payload";
}
