/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const MessageTemplateDto: core.serialization.ObjectSchema<
    serializers.MessageTemplateDto.Raw,
    Novu.MessageTemplateDto
> = core.serialization.object({});

export declare namespace MessageTemplateDto {
    interface Raw {}
}
