/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const MessageTemplate: core.serialization.ObjectSchema<serializers.MessageTemplate.Raw, Novu.MessageTemplate> =
    core.serialization.object({});

export declare namespace MessageTemplate {
    interface Raw {}
}
