/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const NotificationStepMetadataType: core.serialization.Schema<
    serializers.NotificationStepMetadataType.Raw,
    Novu.NotificationStepMetadataType
> = core.serialization.enum_(["regular", "backoff", "scheduled"]);

export declare namespace NotificationStepMetadataType {
    type Raw = "regular" | "backoff" | "scheduled";
}
