/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const NotificationGroup: core.serialization.ObjectSchema<
    serializers.NotificationGroup.Raw,
    Novu.NotificationGroup
> = core.serialization.object({
    id: core.serialization.property("_id", core.serialization.string().optional()),
    name: core.serialization.string(),
    environmentId: core.serialization.property("_environmentId", core.serialization.string()),
    organizationId: core.serialization.property("_organizationId", core.serialization.string()),
    parentId: core.serialization.property("_parentId", core.serialization.string().optional()),
});

export declare namespace NotificationGroup {
    interface Raw {
        _id?: string | null;
        name: string;
        _environmentId: string;
        _organizationId: string;
        _parentId?: string | null;
    }
}
