/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const NotificationStepMetadataBackofUnit: core.serialization.Schema<
    serializers.NotificationStepMetadataBackofUnit.Raw,
    Novu.NotificationStepMetadataBackofUnit
> = core.serialization.enum_(["seconds", "minutes", "hours", "days"]);

export declare namespace NotificationStepMetadataBackofUnit {
    type Raw = "seconds" | "minutes" | "hours" | "days";
}
