/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const NotificationStepMetadataUnit: core.serialization.Schema<
    serializers.NotificationStepMetadataUnit.Raw,
    Novu.NotificationStepMetadataUnit
> = core.serialization.enum_(["seconds", "minutes", "hours", "days"]);

export declare namespace NotificationStepMetadataUnit {
    type Raw = "seconds" | "minutes" | "hours" | "days";
}
