/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const PreferenceChannels: core.serialization.ObjectSchema<
    serializers.PreferenceChannels.Raw,
    Novu.PreferenceChannels
> = core.serialization.object({
    email: core.serialization.boolean().optional(),
    sms: core.serialization.boolean().optional(),
    inApp: core.serialization.property("in_app", core.serialization.boolean().optional()),
    chat: core.serialization.boolean().optional(),
    push: core.serialization.boolean().optional(),
});

export declare namespace PreferenceChannels {
    interface Raw {
        email?: boolean | null;
        sms?: boolean | null;
        in_app?: boolean | null;
        chat?: boolean | null;
        push?: boolean | null;
    }
}
