/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const StepFilterValue: core.serialization.Schema<serializers.StepFilterValue.Raw, Novu.StepFilterValue> =
    core.serialization.enum_(["AND", "OR"]);

export declare namespace StepFilterValue {
    type Raw = "AND" | "OR";
}
