/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Novu } from "@fern-api/novu";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.environments.getAll.Response.Raw,
    Novu.EnvironmentResponseDto[]
> = core.serialization.list(
    core.serialization.lazyObject(async () => (await import("../../..")).EnvironmentResponseDto)
);

export declare namespace Response {
    type Raw = serializers.EnvironmentResponseDto.Raw[];
}
